### ISSUE TITLE
Как заставить работать этот плагин с october cms?

### ISSUE THREAD

**Issue by ipavlin98** [agragregra/uniMail#10]
я пробовал сделать также как и с lending page, ajax выдает успешное сообщение, но на почту ничего не приходит, в чем может быть дело?

**Comment by code-sdv** [comment]
> я пробовал сделать также как и с lending page, ajax выдает успешное сообщение, но на почту ничего не приходит, в чем может быть дело?
Лучше использовать другой скрипт с канала Артема исламова, отправка данных на почту

**Comment by gurovworks** [comment]
Как заставить работать UniMail на WinterCMS
