### ISSUE TITLE
ошибки в работе обоих php скриптов

### ISSUE THREAD

**Issue by haw0k** [agragregra/uniMail#8]
Письма отправояются, но в отладке сети в браузере (Network, Responce в Chrome)
mail.php выдает такую ошибку (PHP Version 5.4.45):
<br />
<b>Notice</b>:  Undefined variable: message in <b>/home/peopleme/medhelper.org/www/mail.php</b> on line <b>20</b><br />

<br>
modx-mail.php вообще не работает, письма не отправляются modx 2.5.7:
<br />
<b>Notice</b>:  Undefined variable: modx in <b>/home/peopleme/medhelper.org/www/modx-mail.php</b> on line <b>9</b><br />
<br />
<b>Fatal error</b>:  Call to a member function getOption() on a non-object in <b>/home/peopleme/medhelper.org/www/modx-mail.php</b> on line <b>9</b><br />

**Comment by Spectrasouls** [comment]
Удалось решить проблему ?

**Comment by haw0k** [comment]
Я не автор скрипта - проблему обнаружил и сообщил. Сам скрипт работает -
пусть и с ошибками

19 окт. 2017 г. 9:38 пользователь "Stanislav" <notifications@github.com>
написал:

**Comment by Spectrasouls** [comment]
скрипт не работает я проверял не отправляет форму . проверял gmail mail yandex

**Comment by wdmcourses** [comment]
@Spectrasouls Скрипт работает. Я проверял )) Следует указывать почту домена в отправителе.

**Comment by Spectrasouls** [comment]
@agragregra Алексей Я не сомневаюсь в вашем опыте и что у вас работает) Я так понимаю что у домена должна быть привязанная либо созданная почта ? Так как остальное будет считать за спам ?

**Comment by wdmcourses** [comment]
Ну да. Обычно техподдержка хоста помогает по таким вопросам.

**Comment by Spectrasouls** [comment]
@agragregra Я в глубине души догадывался зря не проверил свои сомнения до конца  .. Спасибо Вам .

**Comment by EliasBoyko** [comment]
> Ну да. Обычно техподдержка хоста помогает по таким вопросам.

**Comment by EliasBoyko** [comment]
Подскажите, все работало безупречно, шли заказы и вдруг все замолчало! Формы перестали работать. Все работало по умолчанию и отправлялось на почту яндекса. В поддержке отвечают:Отправка почты от имени несуществующего почтового ящика (если вы использовали phpmail - то письма отправлялись от имени сервера) в большинстве случаев фильтруется или отклоняются почтовыми сервисами. По всей вероятности это и произшло в вашем случае. Рекомендации по корректной настройке я вам дал выше.

**Comment by wdmcourses** [comment]
Какая почта у вас в отправителе?

**Comment by EliasBoyko** [comment]
В отправителе Яндекс, Они говорят, что нужно через SMTP подключаться...

**Comment by wdmcourses** [comment]
Не обязательно SMTP. Укажите почту домена, этого будет достаточно. Если удобно работать через интерфейс яндекс почты, привяжите его к вашему ящику.
Что такое почта домена?
yousite.ru - домен
fedya@yousite.ru - его почта
Все это делается в пу хостинга или пишите в поддержку

**Comment by EliasBoyko** [comment]
я правильно понимаю, что почта отправителя указывается тут:?
'From: '.adopt($project_name).' <'.$admin_email.'>' . PHP_EOL .
'Reply-To: '.$admin_email.'' . PHP_EOL;
Если я все правильно понял, то отправка не идет. В логе хоста пишет Client host blocked using spamsource.yandex.ru;

**Comment by wdmcourses** [comment]
Почта домена является почтой отправителя и указывается так, как это показано в инструкции. Для того, чтобы обойти спам фильтры почтовиков вам, как я написал выше, нужно использовать почту домена.

**Comment by EliasBoyko** [comment]
В общем как то странно, указываю как Вы говорите  – письмо не идет. (евробайт) При прочих равных с макхоста все отправляется

**Comment by wdmcourses** [comment]
Попробуйте написать на почту, которую указываете. Приходит письмо? Вы ее вообще создали?
Напишите в поддержку с указанием почты, на которую не идут письма.

**Comment by EliasBoyko** [comment]
Всё раньше работало, все ящики созданы. Буду писать в поддержку. Благодарю за помощь
