### ISSUE TITLE
Как добавить пункт выбора

### ISSUE THREAD

**Issue by panikajo** [agragregra/uniMail#9]
Здравствуйте такой вопрос.
Если я хочу чтобы на мыло отправлялось слово из списка например 

![image](https://user-images.githubusercontent.com/4964185/39686531-3d18ba64-51d2-11e8-9fc3-bf8827c247fb.png)

**Comment by npofopr** [comment]
И в чём проблема? С селектами тоже прекрасно работает

**Comment by panikajo** [comment]
@npofopr Да, и в правду уже все решил). Спасибо.
